version: '3.10'

services:
  telebot:
    build: .
    command: python run_telebot.py
    volumes:
      - .:/usr/src/app
    depends_on:
      - authorization_server

  authorization_server:
    build: .
    command: bash -c "python run_google_auth_server.py && python run_notion_auth_server.py"
    volumes:
      - .:/usr/src/app
    depends_on:
      - worker

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A pkg.msg_brokers worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
