version: '3.10'

services:
  telebot:
    build: .
    command: python run_telebot.py
    volumes:
      - .:/usr/src/app
    depends_on:
      - google_authorization_server
      - notion_authorization_server

  google_authorization_server:
    build: .
    command: python run_google_auth_server.py
    volumes:
      - .:/usr/src/app
    depends_on:
      - worker
    ports:
      - "8080:8080"

  notion_authorization_server:
    build: .
    command: python run_notion_auth_server.py
    volumes:
      - .:/usr/src/app
    depends_on:
      - worker
    ports:
      - "5050:5050"
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A pkg.msg_brokers worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
